* A lone samurai, en route to master ASM

** Basics of Syntax
[[https://www.tutorialspoint.com/assembly_programming/assembly_basic_syntax.htm][Ref]]

*** Division of an ASM program
An assembly program can be divided into 3 parts:
  + the *data* section: The data section is used for declaring initialized data or constants. This data does not change at runtime. You can declare various constant values, file names, or buffer size, etc., in this section.

    Syntax:

        ~section.data~

  + the *bss* section: The bss section is used for declaring variables.

            Syntax:

        ~section.bss~

  + the *text* section: The text section is used for keeping the actual code. This section must begin with the declaration global _start, which tells the kernel where the program execution begins.

            Syntax:

        ~section.text~

        ~global_start~

        ~_start:~


*** Comments
~;~ symbol indicates the start of a comment

*** Syntax of ASM programs
Assembly language statements are entered one statement per line. Each statement follows the following format:

~[label]   mnemonic   [operands]   [;comment]~

+ /fields in `[]` are optional/

Following are some examples of typical assembly language statements:


#+BEGIN_SRC
INC COUNT        ; Increment the memory variable COUNT

MOV TOTAL, 48    ; Transfer the value 48 in the
                 ; memory variable TOTAL

ADD AH, BH       ; Add the content of the
                 ; BH register into the AH register

AND MASK1, 128   ; Perform AND operation on the
                 ; variable MASK1 and 128

ADD MARKS, 10    ; Add 10 to the variable MARKS
MOV AL, 10       ; Transfer the value 10 to the AL register

#+END_SRC
